// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gogo.proto

#include "gogo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace gogoproto {
}  // namespace gogoproto
void InitDefaults_gogo_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_gogo_2eproto = nullptr;
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_gogo_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_gogo_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_gogo_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = nullptr;
static constexpr ::google::protobuf::Message* const* file_default_instances = nullptr;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_gogo_2eproto = {
  {}, AddDescriptors_gogo_2eproto, "gogo.proto", schemas,
  file_default_instances, TableStruct_gogo_2eproto::offsets,
  file_level_metadata_gogo_2eproto, 0, file_level_enum_descriptors_gogo_2eproto, file_level_service_descriptors_gogo_2eproto,
};

const char descriptor_table_protodef_gogo_2eproto[] =
  "\n\ngogo.proto\022\tgogoproto\032 google/protobuf"
  "/descriptor.proto:;\n\023goproto_enum_prefix"
  "\022\034.google.protobuf.EnumOptions\030\261\344\003 \001(\010:="
  "\n\025goproto_enum_stringer\022\034.google.protobu"
  "f.EnumOptions\030\305\344\003 \001(\010:5\n\renum_stringer\022\034"
  ".google.protobuf.EnumOptions\030\306\344\003 \001(\010:7\n\017"
  "enum_customname\022\034.google.protobuf.EnumOp"
  "tions\030\307\344\003 \001(\t:0\n\010enumdecl\022\034.google.proto"
  "buf.EnumOptions\030\310\344\003 \001(\010:A\n\024enumvalue_cus"
  "tomname\022!.google.protobuf.EnumValueOptio"
  "ns\030\321\203\004 \001(\t:;\n\023goproto_getters_all\022\034.goog"
  "le.protobuf.FileOptions\030\231\354\003 \001(\010:\?\n\027gopro"
  "to_enum_prefix_all\022\034.google.protobuf.Fil"
  "eOptions\030\232\354\003 \001(\010:<\n\024goproto_stringer_all"
  "\022\034.google.protobuf.FileOptions\030\233\354\003 \001(\010:9"
  "\n\021verbose_equal_all\022\034.google.protobuf.Fi"
  "leOptions\030\234\354\003 \001(\010:0\n\010face_all\022\034.google.p"
  "rotobuf.FileOptions\030\235\354\003 \001(\010:4\n\014gostring_"
  "all\022\034.google.protobuf.FileOptions\030\236\354\003 \001("
  "\010:4\n\014populate_all\022\034.google.protobuf.File"
  "Options\030\237\354\003 \001(\010:4\n\014stringer_all\022\034.google"
  ".protobuf.FileOptions\030\240\354\003 \001(\010:3\n\013onlyone"
  "_all\022\034.google.protobuf.FileOptions\030\241\354\003 \001"
  "(\010:1\n\tequal_all\022\034.google.protobuf.FileOp"
  "tions\030\245\354\003 \001(\010:7\n\017description_all\022\034.googl"
  "e.protobuf.FileOptions\030\246\354\003 \001(\010:3\n\013testge"
  "n_all\022\034.google.protobuf.FileOptions\030\247\354\003 "
  "\001(\010:4\n\014benchgen_all\022\034.google.protobuf.Fi"
  "leOptions\030\250\354\003 \001(\010:5\n\rmarshaler_all\022\034.goo"
  "gle.protobuf.FileOptions\030\251\354\003 \001(\010:7\n\017unma"
  "rshaler_all\022\034.google.protobuf.FileOption"
  "s\030\252\354\003 \001(\010:<\n\024stable_marshaler_all\022\034.goog"
  "le.protobuf.FileOptions\030\253\354\003 \001(\010:1\n\tsizer"
  "_all\022\034.google.protobuf.FileOptions\030\254\354\003 \001"
  "(\010:A\n\031goproto_enum_stringer_all\022\034.google"
  ".protobuf.FileOptions\030\255\354\003 \001(\010:9\n\021enum_st"
  "ringer_all\022\034.google.protobuf.FileOptions"
  "\030\256\354\003 \001(\010:<\n\024unsafe_marshaler_all\022\034.googl"
  "e.protobuf.FileOptions\030\257\354\003 \001(\010:>\n\026unsafe"
  "_unmarshaler_all\022\034.google.protobuf.FileO"
  "ptions\030\260\354\003 \001(\010:B\n\032goproto_extensions_map"
  "_all\022\034.google.protobuf.FileOptions\030\261\354\003 \001"
  "(\010:@\n\030goproto_unrecognized_all\022\034.google."
  "protobuf.FileOptions\030\262\354\003 \001(\010:8\n\020gogoprot"
  "o_import\022\034.google.protobuf.FileOptions\030\263"
  "\354\003 \001(\010:6\n\016protosizer_all\022\034.google.protob"
  "uf.FileOptions\030\264\354\003 \001(\010:3\n\013compare_all\022\034."
  "google.protobuf.FileOptions\030\265\354\003 \001(\010:4\n\014t"
  "ypedecl_all\022\034.google.protobuf.FileOption"
  "s\030\266\354\003 \001(\010:4\n\014enumdecl_all\022\034.google.proto"
  "buf.FileOptions\030\267\354\003 \001(\010::\n\017goproto_gette"
  "rs\022\037.google.protobuf.MessageOptions\030\201\364\003 "
  "\001(\010:;\n\020goproto_stringer\022\037.google.protobu"
  "f.MessageOptions\030\203\364\003 \001(\010:8\n\rverbose_equa"
  "l\022\037.google.protobuf.MessageOptions\030\204\364\003 \001"
  "(\010:/\n\004face\022\037.google.protobuf.MessageOpti"
  "ons\030\205\364\003 \001(\010:3\n\010gostring\022\037.google.protobu"
  "f.MessageOptions\030\206\364\003 \001(\010:3\n\010populate\022\037.g"
  "oogle.protobuf.MessageOptions\030\207\364\003 \001(\010:3\n"
  "\010stringer\022\037.google.protobuf.MessageOptio"
  "ns\030\300\213\004 \001(\010:2\n\007onlyone\022\037.google.protobuf."
  "MessageOptions\030\211\364\003 \001(\010:0\n\005equal\022\037.google"
  ".protobuf.MessageOptions\030\215\364\003 \001(\010:6\n\013desc"
  "ription\022\037.google.protobuf.MessageOptions"
  "\030\216\364\003 \001(\010:2\n\007testgen\022\037.google.protobuf.Me"
  "ssageOptions\030\217\364\003 \001(\010:3\n\010benchgen\022\037.googl"
  "e.protobuf.MessageOptions\030\220\364\003 \001(\010:4\n\tmar"
  "shaler\022\037.google.protobuf.MessageOptions\030"
  "\221\364\003 \001(\010:6\n\013unmarshaler\022\037.google.protobuf"
  ".MessageOptions\030\222\364\003 \001(\010:;\n\020stable_marsha"
  "ler\022\037.google.protobuf.MessageOptions\030\223\364\003"
  " \001(\010:0\n\005sizer\022\037.google.protobuf.MessageO"
  "ptions\030\224\364\003 \001(\010:;\n\020unsafe_marshaler\022\037.goo"
  "gle.protobuf.MessageOptions\030\227\364\003 \001(\010:=\n\022u"
  "nsafe_unmarshaler\022\037.google.protobuf.Mess"
  "ageOptions\030\230\364\003 \001(\010:A\n\026goproto_extensions"
  "_map\022\037.google.protobuf.MessageOptions\030\231\364"
  "\003 \001(\010:\?\n\024goproto_unrecognized\022\037.google.p"
  "rotobuf.MessageOptions\030\232\364\003 \001(\010:5\n\nprotos"
  "izer\022\037.google.protobuf.MessageOptions\030\234\364"
  "\003 \001(\010:2\n\007compare\022\037.google.protobuf.Messa"
  "geOptions\030\235\364\003 \001(\010:3\n\010typedecl\022\037.google.p"
  "rotobuf.MessageOptions\030\236\364\003 \001(\010:1\n\010nullab"
  "le\022\035.google.protobuf.FieldOptions\030\351\373\003 \001("
  "\010:.\n\005embed\022\035.google.protobuf.FieldOption"
  "s\030\352\373\003 \001(\010:3\n\ncustomtype\022\035.google.protobu"
  "f.FieldOptions\030\353\373\003 \001(\t:3\n\ncustomname\022\035.g"
  "oogle.protobuf.FieldOptions\030\354\373\003 \001(\t:0\n\007j"
  "sontag\022\035.google.protobuf.FieldOptions\030\355\373"
  "\003 \001(\t:1\n\010moretags\022\035.google.protobuf.Fiel"
  "dOptions\030\356\373\003 \001(\t:1\n\010casttype\022\035.google.pr"
  "otobuf.FieldOptions\030\357\373\003 \001(\t:0\n\007castkey\022\035"
  ".google.protobuf.FieldOptions\030\360\373\003 \001(\t:2\n"
  "\tcastvalue\022\035.google.protobuf.FieldOption"
  "s\030\361\373\003 \001(\t:0\n\007stdtime\022\035.google.protobuf.F"
  "ieldOptions\030\362\373\003 \001(\010:4\n\013stdduration\022\035.goo"
  "gle.protobuf.FieldOptions\030\363\373\003 \001(\010B!\n\023com"
  ".google.protobufB\nGoGoProtos"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_gogo_2eproto = {
  false, InitDefaults_gogo_2eproto, 
  descriptor_table_protodef_gogo_2eproto,
  "gogo.proto", &assign_descriptors_table_gogo_2eproto, 3908,
};

void AddDescriptors_gogo_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
    ::AddDescriptors_google_2fprotobuf_2fdescriptor_2eproto,
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_gogo_2eproto, deps, 1);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_gogo_2eproto = []() { AddDescriptors_gogo_2eproto(); return true; }();
namespace gogoproto {
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_prefix(kGoprotoEnumPrefixFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_stringer(kGoprotoEnumStringerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enum_stringer(kEnumStringerFieldNumber, false);
const ::std::string enum_customname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enum_customname(kEnumCustomnameFieldNumber, enum_customname_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enumdecl(kEnumdeclFieldNumber, false);
const ::std::string enumvalue_customname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  enumvalue_customname(kEnumvalueCustomnameFieldNumber, enumvalue_customname_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_getters_all(kGoprotoGettersAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_prefix_all(kGoprotoEnumPrefixAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_stringer_all(kGoprotoStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  verbose_equal_all(kVerboseEqualAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  face_all(kFaceAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  gostring_all(kGostringAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  populate_all(kPopulateAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stringer_all(kStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  onlyone_all(kOnlyoneAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  equal_all(kEqualAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  description_all(kDescriptionAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  testgen_all(kTestgenAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  benchgen_all(kBenchgenAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  marshaler_all(kMarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unmarshaler_all(kUnmarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stable_marshaler_all(kStableMarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  sizer_all(kSizerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_enum_stringer_all(kGoprotoEnumStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enum_stringer_all(kEnumStringerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_marshaler_all(kUnsafeMarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_unmarshaler_all(kUnsafeUnmarshalerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_extensions_map_all(kGoprotoExtensionsMapAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_unrecognized_all(kGoprotoUnrecognizedAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  gogoproto_import(kGogoprotoImportFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  protosizer_all(kProtosizerAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  compare_all(kCompareAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  typedecl_all(kTypedeclAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  enumdecl_all(kEnumdeclAllFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_getters(kGoprotoGettersFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_stringer(kGoprotoStringerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  verbose_equal(kVerboseEqualFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  face(kFaceFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  gostring(kGostringFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  populate(kPopulateFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stringer(kStringerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  onlyone(kOnlyoneFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  equal(kEqualFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  description(kDescriptionFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  testgen(kTestgenFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  benchgen(kBenchgenFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  marshaler(kMarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unmarshaler(kUnmarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stable_marshaler(kStableMarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  sizer(kSizerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_marshaler(kUnsafeMarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  unsafe_unmarshaler(kUnsafeUnmarshalerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_extensions_map(kGoprotoExtensionsMapFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  goproto_unrecognized(kGoprotoUnrecognizedFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  protosizer(kProtosizerFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  compare(kCompareFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  typedecl(kTypedeclFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  nullable(kNullableFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  embed(kEmbedFieldNumber, false);
const ::std::string customtype_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  customtype(kCustomtypeFieldNumber, customtype_default);
const ::std::string customname_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  customname(kCustomnameFieldNumber, customname_default);
const ::std::string jsontag_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  jsontag(kJsontagFieldNumber, jsontag_default);
const ::std::string moretags_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  moretags(kMoretagsFieldNumber, moretags_default);
const ::std::string casttype_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  casttype(kCasttypeFieldNumber, casttype_default);
const ::std::string castkey_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  castkey(kCastkeyFieldNumber, castkey_default);
const ::std::string castvalue_default("");
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::StringTypeTraits, 9, false >
  castvalue(kCastvalueFieldNumber, castvalue_default);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stdtime(kStdtimeFieldNumber, false);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false >
  stdduration(kStddurationFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)
}  // namespace gogoproto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
